package(default_visibility = ["//visibility:public"])

filegroup(
    name = "golden_files",
    srcs = [
        "cli.version.golden",
        "cli.no-args.golden",
        "cli.auth.golden",
        "api.signup.golden",
    ],
)
